// Pipeline Jenkins pentru build, push și deploy al scriptului Bash de monitorizare
pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'marcu001'
        IMAGE_NAME = 'system-monitor'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonăm repository-ul...'
                git branch: 'main', url: 'https://github.com/MarcuCalin/Platforma-monitorizare.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Construim imaginea Docker pentru sistemul de monitorizare...'
                sh '''
                    apt update && apt install -y docker.io
                    docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:latest -f ../../docker/Dockerfile.monitoring .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Publicăm imaginea în Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest
                        docker logout
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy cu Ansible...'
                sh '''
                    apt install -y ansible openssh-client
                    ansible-playbook ansible/playbooks/deploy_platform.yml -i ../../ansible/inventory.ini
                '''
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Ștergem imaginea locală temporară...'
                sh 'docker rmi ${DOCKERHUB_USER}/${IMAGE_NAME}:latest || true'
            }
        }
    }

    post {
        success { echo 'Pipeline monitoring finalizat cu succes!' }
        failure { echo 'Pipeline monitoring eșuat!' }
    }
}
