apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring
spec:
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
